name = "contentlayer-nextjs-github-admin"
compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[env.production]
name = "contentlayer-nextjs-github-admin"
